NGD: false
TEST: true
batch_size: 32
dataset: MNIST
layer_type: MLP
lr: 0.2976
n_e: 500
n_epochs: 50
n_hidden: 3
n_i: 0
results_save_dir: ./results/mnist_mlp
seeds:
- 1
selected_params:
- dataset
- layer_type
- lr
- batch_size
- n_e
- n_i
- n_epochs
- TEST
